from pydantic import BaseModel
from typing import Optional, List

from app.core.baseSchema import MdlBaseRequest, MdlBaseResponse


class MdlAIQuotationItem(BaseModel):
    """Single item generated by AI"""
    strItemName: str
    strItemCode: Optional[str] = None
    intInventoryId: Optional[int] = None
    dblQuantity: float
    dblUnitPrice: float
    strUnit: Optional[str] = "piece"


class MdlProcessQuotationRequest(MdlBaseRequest):
    """Request to process raw text into quotation items"""
    strRawText: str  # Raw text like "2 cameras, 1 DVR, wiring..."


class MdlProcessQuotationResponse(MdlBaseResponse):
    """Response with AI-generated quotation items"""
    lstItems: List[MdlAIQuotationItem] = []
    strCustomerName: Optional[str] = None
    strCustomerPhone: Optional[str] = None
    strNotes: Optional[str] = None
